
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import java.util.Date;

public class Test5 extends javax.swing.JFrame {

    private DefaultTableModel mod;
    private PreparedStatement ps;
    private String sql;
    private ResultSet r;

    public Test5() {
        initComponents();
        ImageIcon Icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("featured_channel.jpg")));
        Image img1 = Icon.getImage();
        Image img2 = img1.getScaledInstance(Label.getWidth(), Label.getHeight(), Image.SCALE_SMOOTH);

        ImageIcon i = new ImageIcon(img2);
        Label.setIcon(i);
    }


    Connection connection() {
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student", "root", "");

        } catch (ClassNotFoundException | SQLException ex) {
            System.err.println("Error Connection...!" + ex.getMessage());
        }
        return con;
    }

    private void SetTable() {
        try {
            sql = "SELECT * FROM stu_info";
            ps = connection().prepareStatement(sql);
            r = ps.executeQuery();
            while (r.next()) {
                mod = (DefaultTableModel) ttable.getModel();
                String id = r.getString(1);
                String name = r.getString(2);
                String sex = r.getString(3);
                String date = r.getString(4);
                String subject = r.getString(5);
                String time = r.getString(6);
                String phone = r.getString(7);
                Object[] row = {id, name, sex, date, subject, time, phone};
                mod.addRow(row);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    private void clear() {
        txtid.setText("AUTO - ID");
        txtname.setText("");
        rmale.setSelected(true);
        txtdate.setText("");
        txtsub.setSelectedIndex(0);
        txttime.setText("");
        txtphone.setText("");
        mod.setRowCount(0);

        SetTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        txtsub = new javax.swing.JComboBox<>();
        txttime = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        updatebt = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ETEC CENTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(681, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 974, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student - ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student - Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student - Sex : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student - Date : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student - SubJect : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student - Time: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 20));

        rmale.setBackground(new java.awt.Color(102, 102, 102));
        rmale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rmale.setForeground(new java.awt.Color(255, 255, 255));
        rmale.setText("Male");
        rmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmaleActionPerformed(evt);
            }
        });
        getContentPane().add(rmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 70, 20));

        rfemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rfemale.setForeground(new java.awt.Color(255, 255, 255));
        rfemale.setText("Female");
        getContentPane().add(rfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        txtsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C++", "Java", "PHP", "Python" }));
        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });
        getContentPane().add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 190, 30));
        getContentPane().add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 190, 30));

        txtid.setText("AUTO - ID");
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 190, 30));
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 190, 30));
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 190, 30));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 30));

        ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sex", "Date", "Subject", "Time", "Phone"
            }
        ));
        ttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 520, 200));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, -1, -1));

        btsave.setText("SAVE");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        updatebt.setText("UPDATE");
        updatebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtActionPerformed(evt);
            }
        });
        getContentPane().add(updatebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });
        getContentPane().add(btclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 80, 80));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 310, 30));

        jButton2.setText("Image");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 142, 80, 30));

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s11.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 970, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmaleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SetTable();
    }//GEN-LAST:event_formWindowOpened

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed

        try {
            String name = txtname.getText();
            String sex;
            if (rmale.isSelected()) {
                sex = "Male";
            } else {
                sex = "Female";
            }

            String date = txtdate.getText();
            String time = txttime.getText();
            String phone = txtphone.getText();
            String subject = txtsub.getSelectedItem().toString();
            //  InputStream img = new FileInputStream(new File (imgPath));
            sql = "INSERT INTO stu_info(name, sex, date, subject, time,phone) VALUES (?,?,?,?,?,?)";
            ps = connection().prepareStatement(sql);
            ps.setString(1, name);
            ps.setString(2, sex);
            ps.setString(3, date);
            ps.setString(4, subject);
            ps.setString(5, time);
            ps.setString(6, phone);
            //ps.setBlob (7, img);
            int index = ps.executeUpdate();
            if (index > 0) {
                JOptionPane.showMessageDialog(this, "Staff information saved...!");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "save faile...!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttableMouseClicked
        int row = ttable.getSelectedRow();
        txtname.setText(mod.getValueAt(row, 1).toString());
        String sex = mod.getValueAt(row, 2).toString();
        if (sex.equals("Male")) {
            rmale.setSelected(true);
            rfemale.setSelected(false);
        } else {
            rmale.setSelected(false);
            rfemale.setSelected(true);
        }
        txtdate.setText(mod.getValueAt(row, 3).toString());
        String subject = mod.getValueAt(row, 4).toString();
        switch (subject) {
            case "C++": {
                txtsub.setSelectedIndex(0);
            }
            break;
            case "Java": {
                txtsub.setSelectedIndex(1);
            }
            break;
            case "PHP":
                txtsub.setSelectedIndex(2);
                break;
            case "Python":
                txtsub.setSelectedIndex(3);
                break;

        }
        txttime.setText(mod.getValueAt(row, 5).toString());
        txtphone.setText(mod.getValueAt(row, 6).toString());

    }//GEN-LAST:event_ttableMouseClicked

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubActionPerformed

    private void updatebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtActionPerformed

        mod = (DefaultTableModel)ttable.getModel();
        int selectedIndex = ttable.getSelectedRow();
        try {
            
            int id = Integer.parseInt(mod.getValueAt(selectedIndex, 0).toString());
            String name = this.txtname.getText();
            String sex;
            if (this.rmale.isSelected()) {
                sex = "Male";
            } else {
                sex = "Female";
            }
            String date = this.txtdate.getText();
            String subject = this.txtsub.getSelectedItem().toString();
            String time = this.txttime.getText();
            String phone = this.txtphone.getText();
            sql = "UPDATE stu_info SET name =?,sex=?,date=?,subject=?, time=?,phone=? WHERE id=?";

            ps = connection().prepareStatement(sql);
            ps.setString(1, name);
            ps.setString(2, sex);
            ps.setString(3, date);
            ps.setString(4, subject);
            ps.setString(5, time);
            ps.setString(6, phone);
            ps.setInt (7, id);
            int index = ps.executeUpdate();
            if (index > 0) {
                JOptionPane.showMessageDialog(this, "Informaton update succeful...!");
            } else {
                JOptionPane.showMessageDialog(this, "Update Error...!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            SetTable();
            clear();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }


    }//GEN-LAST:event_updatebtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mod = (DefaultTableModel) ttable.getModel();
        int selectedIndex = ttable.getSelectedRow();
        
        try {
            int id = Integer.parseInt(mod.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete...?","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                sql = "DELETE FROM stu_info WHERE id =?";
                ps = connection().prepareStatement(sql);
                ps.setInt(1,id);
                int index = ps.executeUpdate();
                if(index > 0){
                    JOptionPane.showMessageDialog(this, "Staff has Deleted...?");
                }else{
                    JOptionPane.showMessageDialog(this, "Error Delete...?","Warnning",JOptionPane.ERROR_MESSAGE);
                }
                SetTable();
                clear();
            }
          
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        clear();
    }//GEN-LAST:event_btclearActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTable ttable;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JComboBox<String> txtsub;
    private javax.swing.JTextField txttime;
    private javax.swing.JButton updatebt;
    // End of variables declaration//GEN-END:variables
}
